## Analysis part2

In [1]:
from IPython.core import display as ICD
import pandas as pd
import glob, os
from sklearn import svm

In [2]:
data_file = "gamma_twomice_speed_cats.xlsx"

In [3]:
df = pd.read_excel(data_file)

In [4]:
df.move.unique()

array([1, 2, 0])

In [22]:
clf=svm.SVC()

In [23]:
clf.fit(X, y)

/Users/nikkibytes/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
df

Time  id  VTA01_Gamma (35-80)  VTA02_Gamma (35-80)  VTA03_Gamma (35-80)  \
0        0   1           -55.455906           -56.544137           -55.854948   
1        1   1           -55.745437           -54.423164           -55.350601   
2        2   1           -53.511543           -53.417340           -53.989995   
3        3   1           -55.346259           -55.889945           -55.890227   
4        4   1           -55.547062           -53.365827           -55.138734   
...    ...  ..                  ...                  ...                  ...   
2395  1195   2           -58.177812           -53.722837           -55.860257   
2396  1196   2           -58.260384           -54.273384           -56.172787   
2397  1197   2           -57.573694           -52.809696           -55.657694   
2398  1198   2           -59.148401           -56.383166           -58.143082   
2399  1199   2           -58.037833           -53.719803           -55.992795   

      VTA04_Gamma (35-80)  BLA01_Gamma (35-80)  BLA02_Gamma (35-80)  \
0              -54.553870           -52.680928           -52.848247   
1              -56.033353           -52.801738           -52.474410   
2              -54.550385           -53.745198           -53.620413   
3              -56.110035           -55.588631           -55.708550   
4              -55.942671           -52.426493           -52.630225   
...                   ...                  ...                  ...   
2395           -55.021091           -52.399610           -52.810936   
2396           -53.654925           -51.236688           -50.904866   
2397           -54.720435           -50.767034           -50.599928   
2398           -54.676640           -49.653068           -49.751026   
2399           -57.394977           -49.553240           -49.229310   

      BLA03_Gamma (35-80)  BLA04_Gamma (35-80)  NAc01_Gamma (35-80)  \
0              -52.708793           -52.745989           -54.758013   
1              -52.789465           -52.688538           -54.077320   
2              -53.918141           -53.761251           -53.296488   
3              -55.565186           -55.620789           -57.916630   
4              -52.541053           -52.532590           -55.066862   
...                   ...                  ...                  ...   
2395           -52.874088           -52.453481           -51.571879   
2396           -50.879077           -51.208627           -50.369885   
2397           -50.629818           -50.754870           -51.887212   
2398           -49.725145           -49.659155           -51.439360   
2399           -49.202894           -49.645708           -51.659875   

      NAc02_Gamma (35-80)  NAc03_Gamma (35-80)  NAc04_Gamma (35-80)  \
0              -54.731863           -54.738937           -54.635744   
1              -54.021614           -54.045362           -54.232185   
2              -53.375627           -53.264524           -53.309571   
3              -57.816757           -57.866756           -57.791698   
4              -55.041142           -54.987115           -54.986182   
...                   ...                  ...                  ...   
2395           -51.599643           -52.004744           -51.730452   
2396           -50.281313           -50.776763           -50.541848   
2397           -51.894632           -52.338197           -52.088700   
2398           -51.584404           -52.127659           -51.944724   
2399           -51.705361           -51.764227           -51.871246   

      PFC01_Gamma (35-80)  PFC02_Gamma (35-80)  PFC03_Gamma (35-80)  \
0              -52.150338           -52.258260           -52.303187   
1              -49.507135           -49.548199           -49.504652   
2              -51.673439           -51.649943           -51.636795   
3              -52.771802           -52.762355           -52.737476   
4              -53.060271           -52.773957           -52.810906   
...                   ...                  ...  

In [11]:
df.columns.values

array(['Time', 'id', 'VTA01_Gamma (35-80)', 'VTA02_Gamma (35-80)',
       'VTA03_Gamma (35-80)', 'VTA04_Gamma (35-80)',
       'BLA01_Gamma (35-80)', 'BLA02_Gamma (35-80)',
       'BLA03_Gamma (35-80)', 'BLA04_Gamma (35-80)',
       'NAc01_Gamma (35-80)', 'NAc02_Gamma (35-80)',
       'NAc03_Gamma (35-80)', 'NAc04_Gamma (35-80)',
       'PFC01_Gamma (35-80)', 'PFC02_Gamma (35-80)',
       'PFC03_Gamma (35-80)', 'PFC04_Gamma (35-80)', 'Speed(cm/s)',
       'move'], dtype=object)

In [6]:
X=df[['VTA03_Gamma (35-80)', 'VTA04_Gamma (35-80)',
       'BLA01_Gamma (35-80)', 'BLA02_Gamma (35-80)',
       'BLA03_Gamma (35-80)', 'BLA04_Gamma (35-80)',
       'NAc01_Gamma (35-80)', 'NAc02_Gamma (35-80)',
       'NAc03_Gamma (35-80)', 'NAc04_Gamma (35-80)',
       'PFC01_Gamma (35-80)', 'PFC02_Gamma (35-80)',
       'PFC03_Gamma (35-80)', 'PFC04_Gamma (35-80)']].to_numpy()

In [7]:
X

array([[-55.85494772, -54.55387036, -52.68092845, ..., -52.25825993,
        -52.30318691, -52.25350735],
       [-55.35060083, -56.03335328, -52.80173785, ..., -49.54819915,
        -49.50465157, -49.54108787],
       [-53.98999523, -54.5503854 , -53.74519813, ..., -51.64994313,
        -51.63679522, -51.66818493],
       ...,
       [-55.65769367, -54.72043515, -50.7670339 , ..., -52.98455557,
        -53.32127526, -52.88475728],
       [-58.14308218, -54.67663987, -49.65306813, ..., -52.9344017 ,
        -52.70371702, -53.13698454],
       [-55.99279523, -57.39497709, -49.55324026, ..., -53.56824276,
        -53.31523039, -54.52538457]])

In [8]:
X.shape

(2400, 14)

In [9]:
y=df['move']

In [10]:
clf = svm.SVC()
clf.fit(X, y)


/Users/nikkibytes/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [11]:
y_pred=clf.predict(X)

In [12]:
y_pred

array([2, 2, 2, ..., 2, 2, 2])

In [13]:
from sklearn.feature_selection import SelectKBest, f_classif
feature_selection = SelectKBest(f_classif, k=-1)

# We have our classifier (SVC), our feature selection (SelectKBest), and now,
# we can plug them together in a *pipeline* that performs the two operations
# successively:
from sklearn.pipeline import Pipeline
anova_svc = Pipeline([('anova', feature_selection), ('svc', clf)])

In [17]:
from sklearn.model_selection import GridSearchCV, cross_val_score
# We are going to tune the parameter 'k' of the step called 'anova' in
# the pipeline. Thus we need to address it as 'anova__k'.
k_range = [10, 15, 30, 50, 150, 300, 500, 1000, 1500, 3000, 5000]


grid = GridSearchCV(clf, param_grid={'svc__k': k_range}, verbose=1)
nested_cv_scores = cross_val_score(grid, X, y, cv=3)
print("Nested CV score: %.4f" % np.mean(nested_cv_scores))


Fitting 3 folds for each of 11 candidates, totalling 33 fits


/Users/nikkibytes/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/nikkibytes/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:530: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


ValueError: Invalid parameter svc for estimator SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False). Check the list of available parameters with `estimator.get_params().keys()`.